### ISSUE TITLE
Video is not the same as that project

### ISSUE THREAD

**Issue by alucardeht** [afgprogrammer/Flutter-Splash-Screen-Animation#1]

**Comment by afgprogrammer** [comment]
What is the problem?

**Comment by fasrinaleem** [comment]
> What is the problem?

I think @alucardeht is meant that you forgot to show the files that you are importing. That's not a big deal I guess. I also did the development by watching that video. I just took this code just only as a backup plan. I wrote the code on my own just only by watching that video. There is nothing goes wrong for me.

Thank you @afgprogrammer for your video and source code.

**Comment by afgprogrammer** [comment]
@fasrinaleem I thought I have forgotten something to show in my video but when I double-checked the video and code, I could not find anything left in the video.

Thank you too :)
